name: Publish to npm

on:
  push:
    branches:
      - main  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Install dependencies
      run: npm install

    - name: Publish to npm
      run: |
        npm version patch  # Or use minor/major depending on your versioning needs
        npm publish --access public  # Ensure the package is public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
